site_name: Bitsec Documentation
site_description: Documentation for Bitsec.ai, building AI security agents that replace security researchers.
repo_url: https://github.com/Bitsec-AI/docs

theme:
  name: material
  icon:
    logo: material/shield-outline
    edit: material/pencil
    search: material/magnify
    repo: material/github
  favicon: assets/shield-outline.png

  palette:
    - scheme: default # Light mode
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate # Dark mode
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
